PeoductCRUD/Models/SP.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PeoductCRUD.Models
{
    public class SP
    {
        public string id { get; set; }
        public string ten { get; set; }
        public string loai { get; set; }
        public int gia { get; set; }
        public string mota { get; set; }
        public string brand { get; set; }
        public string img { get; set; }

    }
}

PeoductCRUD/Controllers/SPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using PeoductCRUD.Models;

namespace PeoductCRUD.Controllers
{
    public class SPController : Controller
    {
        
        public IActionResult Index()
        {
            SPContext context = HttpContext.RequestServices.GetService(typeof(PeoductCRUD.Models.SPContext)) as SPContext;

            return View(context.GetAllAlbums());
        }

        public IActionResult SinglePage(string id)
        {
            
            SPContext context = HttpContext.RequestServices.GetService(typeof(PeoductCRUD.Models.SPContext)) as SPContext;

            return View(context.GetSinhgleSP(id));
        }
        public IActionResult AddtoCart(string id, string sl, string name)
        {
            SPContext context = HttpContext.RequestServices.GetService(typeof(PeoductCRUD.Models.SPContext)) as SPContext;
            context.AddtoCart(id,sl,name);
            return RedirectToAction("Index");

        }
        
    }
}

PeoductCRUD/Views/SP/Index.cshtml
@model IEnumerable<PeoductCRUD.Models.SP>
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Index";
    var name = @Context.Session.GetString("KhachHang");
}


<div class="container" style="background-image">
    <div class="grid-container">

        @foreach (var item in Model)
        {
            <div class="grid-item">
                <tr>
                    <button>
                        <img src="~/Data/img/@Html.DisplayFor(modelItem => item.img)" width="180" height="200">
                    </button>
                </tr>
                <tr>
                    <h3> @Html.DisplayFor(modelItem => item.brand)</h3>
                </tr>
                <tr>
                    <h7>
                        @Html.DisplayFor(modelItem => item.ten)
                    </h7>
                </tr>
                <br>
                <tr>
                    <strong>
                        $ @Html.DisplayFor(modelItem => item.gia)
                    </strong>
                </tr>
                <br>
                <a asp-controller="SP" asp-action="AddtoCart" asp-route-id="@item.id" asp-route-sl="1" asp-route-name=@name class="btn btn-outline-success" type="button">Add to cart</a>
                <a asp-controller="SP" asp-action="SinglePage" asp-route-id="@item.id" class="btn btn-outline-primary" type="button">More info</a>


            </div>
        }
    </div>
</div>
<style>
    .grid-container {
        display: grid;
        grid-gap: 20px 20px;
        grid-template-columns: auto auto auto auto;
        padding: 5px;
        background-color: #ffb3b3;
    }

    .grid-item {
        background-color: #ff9999;
        padding: 5px;
        text-align: center;
        width: 250px;
    }
</style>

PeoductCRUD/Views/SP/SinglePage.cshtml
@model PeoductCRUD.Models.SP

@{
    ViewData["Title"] = "SinglePage";
    ViewData["user"] = "Huy";
    
}
<div class="container">
<h1>Single Page</h1>

<div>
    <h4>SP @Model.id</h4>
    <hr />

    <div class="row">
        <div class="col-sm-6">
            <img src="~/Data/img/@Html.DisplayFor(model => model.img)" width="500px" height="500px" />
        </div>
        <div class="col-sm-6">
            <div class="col-sm-10">
                @Html.DisplayFor(model => model.brand)
            </div>
            <div class="col-sm-10" style="font-size:40px">
                @Html.DisplayFor(model => model.ten)
            </div>
            <div class="col-sm-10" style="font-size:30px">
                <strong>
                    $ @Html.DisplayFor(model => model.gia)
                </strong>
            </div>
            
            <div class="col-sm-10" style="font-size:15px">
                @Html.DisplayFor(model => model.mota)
            </div>

            <div class="col-sm-10" style="font-size:25px;text-align:end;align-items: flex-end;display: flex;height:300px;justify-content: space-between">
                <a asp-controller="SP" asp-action="AddtoCart" asp-route-id="@Model.id" asp-route-sl="1"  asp-route-name="@ViewData["user"]" class="btn btn-outline-success" type="button">Add to cart</a>
                <a asp-controller="SP" asp-action="Index" class="btn btn-outline-danger" type="button">Back to shopping</a>
            </div>
        </div>
    </div>
    
</div>